{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import function_mes as mes\n",
    "import pandas as pd\n",
    "print()\n",
    "st.sidebar.title(\"WORKFLOW\")\n",
    "start=True\n",
    "if st.sidebar.button(\"Getting Started\") or start==True:\n",
    "    # TODO: \"\"\"Do instruction to help pepole understand process\"\"\"\n",
    "    # TODO: \n",
    "    st.title(\"**NO-MES**: **N**ot-**O**nly-**M**es \")\n",
    "    st.write(\"* Application provide advanced setup workflow for enginnering to prevent missing setup and aim to setup MES/ACS data just 5 minute as ACSonetool used to.\")\n",
    "    st.write('* Workflow: ')\n",
    "    \n",
    "    #TAG \"\"\"End \"\"\"\n",
    "\n",
    "# st.graphviz_chart('''\n",
    "# digraph g {\n",
    "# \trankdir=LR;\n",
    "\n",
    "# \tnode [shape=rpromoter colorscheme=rdbu5 color=1 style=filled fontcolor=3]; Hef1a; TRE; UAS; Hef1aLacOid;\n",
    "# \tHef1aLacOid [label=\"Hef1a-LacOid\"];\n",
    "# \tnode [shape=rarrow colorscheme=rdbu5 color=5 style=filled fontcolor=3]; Gal4VP16; LacI; rtTA3; DeltamCherry;\n",
    "# \tGal4VP16 [label=\"Gal4-VP16\"];\t\n",
    "# \tproduct [shape=oval style=filled colorscheme=rdbu5 color=2 label=\"\"];\n",
    "# \trepression [shape=oval label=\"LacI repression\" fontcolor=black style=dotted];\n",
    "# \tnode [shape=oval style=filled colorscheme=rdbu5 color=4 fontcolor=5];\n",
    "# \tcombination [label=\"rtTA3 + Doxycycline\"];\n",
    "# \tLacIprotein [label=\"LacI\"];\n",
    "# \trtTA3protein [label=\"rtTA3\"];\n",
    "# \tGal4VP16protein [label=\"Gal4-VP16\"];\n",
    "\t\n",
    "\n",
    "# \tsubgraph cluster_0 {\n",
    "# \t\tcolorscheme=rdbu5;\n",
    "# \t\tcolor=3;\n",
    "# \t\tnode [colorscheme=rdbu5 fontcolor=3];\n",
    "# \t\tHef1a -> Gal4VP16 [arrowhead=none];\n",
    "# \t\tGal4VP16 -> UAS [arrowhead=none];\n",
    "# \t\tUAS -> LacI [arrowhead=none];\n",
    "# \t\tLacI -> Hef1aLacOid [arrowhead=none];\n",
    "# \t\tHef1aLacOid -> rtTA3 [arrowhead=none];\n",
    "# \t\trtTA3 -> TRE [arrowhead=none];\n",
    "# \t\tTRE -> DeltamCherry [arrowhead=none]\n",
    "# \t}\n",
    "\t\n",
    "# \tGal4VP16 -> Gal4VP16protein;\n",
    "# \tGal4VP16protein -> UAS;\n",
    "# \tLacI -> LacIprotein;\n",
    "# \tLacIprotein -> repression;\n",
    "# \trepression -> Hef1aLacOid [arrowhead=tee];\n",
    "# \tIPTG -> repression [arrowhead=tee];\n",
    "# \trtTA3 -> rtTA3protein;\n",
    "# \trtTA3protein -> combination;\n",
    "# \tcombination -> TRE;\n",
    "# \tDoxycycline -> combination;\n",
    "# \tDeltamCherry -> product;\n",
    "\t\n",
    "\t\n",
    "\t\t\n",
    "# }\n",
    "\n",
    "# ''')\n",
    "\n",
    "    st.graphviz_chart('''\n",
    "        digraph {\n",
    "            order -> list_kitting\n",
    "            order -> model\n",
    "            model -> BOM_bom_routing\n",
    "            model -> ROUTING_bom_routing\n",
    "            model -> SW_is_exist\n",
    "            SW->SW_LOCATION\n",
    "\n",
    "            BOM_bom_routing -> sleep\n",
    "            order -> BOM_PO\n",
    "            BOM_PO -> LABEL\n",
    "            BOM_PO -> OPERATION\n",
    "            order -> SFC\n",
    "            LABEL -> LABEL_SETUP\n",
    "            LABEL_SETUP -> LABEL_LOCATION\n",
    "            LABEL -> OK_SETUP\n",
    "            LABEL -> WRONG_SETUP\n",
    "            LABEL -> MISSING_SETUP\n",
    "        }\n",
    "    ''')\n",
    "site=st.sidebar.selectbox(\"plant\",[3400,2600])\n",
    "report_type=st.sidebar.selectbox(\"Start with ShopOrder/Material/SFC\",[\"ShopOrder\",\"Material\",\"SFC\",\"ASSY tracking up/down\"])\n",
    "\n",
    "\n",
    "#-------------------------\n",
    "\n",
    "def track_sfc_to_po(site,sfc):\n",
    "\n",
    "    table='SFC' \n",
    "    df=mes.mesquery(\"\"\"\n",
    "            select * from WPPUSER.{0}  \n",
    "\n",
    "                where ROWNUM <10    \n",
    "                and site ='{1}'\n",
    "    --and sfc_router_bo like '%G19NAQMDM%'\n",
    "    and sfc='{2}'\n",
    "             \"\"\".format(table,site,sfc))\n",
    "\n",
    "    #sfc_bom_bo top_down\n",
    "    #inventory_bo bot_up\n",
    "#     print(df.columns)\n",
    "#     print(df.head(1).T)\n",
    "    last_record=df.head(1)\n",
    "    _shop_order_bo = last_record[\"shop_order_bo\"].values\n",
    "#     print(_shop_order_bo)\n",
    "    _shop_order=_shop_order_bo[0].split(\",\")[1]\n",
    "#     print(_shop_order)\n",
    "# print(mes_datatype(table))\n",
    "#     print(fr\"test: sfc_to_po(3400,\"G19NAQMDM\")\")\n",
    "    return _shop_order\n",
    "# track_sfc_to_po(3400,\"G19NAQMDM\")\n",
    "\n",
    "bool_order=False\n",
    "#----------------------------------\n",
    "if report_type ==\"SFC\":\n",
    "    sfc=st.sidebar.text_input(\"SFC\",\"G19NAQMDM\")\n",
    "    if st.sidebar.button(\"track sfc to po\"):\n",
    "        po_sfc=track_sfc_to_po(site,sfc)\n",
    "        st.sidebar.text(\"PO: {}\".format( po_sfc))\n",
    "#         report_type =\"ShopOrder\"\n",
    "#         bool_order=True\n",
    "#         po=st.sidebar.text_input(\"Nhập PO\",po_sfc)\n",
    "        \n",
    "if report_type ==\"ShopOrder\" :\n",
    "    \n",
    "    po = st.sidebar.text_input(\"Nhập PO\",\"101333846\").strip()\n",
    "\n",
    "\n",
    "#     po=po.split('\\n')\n",
    "#     #send list to have list complate\n",
    "#     while '' in po:\n",
    "#         po.remove('')\n",
    "\n",
    "\n",
    "\n",
    "    #-----------------------\n",
    "\n",
    "    if st.sidebar.button(\"CHECK MES\"):\n",
    "        start=False\n",
    "        st.sidebar.text(\"---start {}---\".format(site))\n",
    "        st.sidebar.text(\"ShopOrder: {}\".format(po))\n",
    "        df= mes.mesquery(\"\"\"\n",
    "         select * from WPPUSER.ZME_KITTING WHERE 1=1 \n",
    "                 and SHOP_ORDER_BO LIKE '%{}%'  \n",
    "                 AND SITE ='3400'\n",
    "                AND assigned_start_date >= (SYSDATE -3) AND assigned_start_date <= (SYSDATE +3)\n",
    "\n",
    "\n",
    "                order by assigned_start_date desc\n",
    "\n",
    "        \"\"\".format(po)    )\n",
    "        def order_status(r):\n",
    "            return str(r[\"shop_order_bo\"].split(\",\")[1]) +str( \"-deleted\" if r['fl_delete'] ==\"X\" else \"\")\n",
    "\n",
    "#         df.insert (0, \"Order\", df.shop_order_bo.apply(lambda r: r.split(\",\")[1]))\n",
    "        df.insert (0, \"Order\", df.apply(order_status, axis=1))\n",
    "\n",
    "        st.subheader(\"Step: Check Kitting ,Count order {} , PO#: {}\".format(len(df),po))\n",
    "        st.table(df)\n",
    "        model=df.item.iloc[0]\n",
    "        sapwc=df.primary_work_center.iloc[0]\n",
    "        meswc=df.work_center.iloc[0]\n",
    "        qty=df.qty_to_build.iloc[0]\n",
    "    #     st.write(\"Sap_model: {}\".format(model))\n",
    "        st.sidebar.text(\"Model :{} \".format(model))\n",
    "        st.sidebar.text(\"Qty: {}\".format(qty))\n",
    "        st.sidebar.text(\"SAP WC: {} \".format(sapwc))\n",
    "        st.sidebar.text(\"MES WC: {} \".format(meswc))\n",
    "        st.sidebar.text(\"MES delete: {} \".format(df.fl_delete.iloc[0]))\n",
    "        \n",
    "        list_allorder=df.shop_order_bo.apply(lambda r: r.split(\",\")[1]).values\n",
    "#         myTuple = [\"John\", \"Peter\", \"Vicky\"]\n",
    "        query=\"'{}'\".format(list_allorder[0])\n",
    "        for x in list_allorder[1:]:\n",
    "            query=query + \",'{}'\".format(x)\n",
    "#         query\n",
    "        #---------------------\n",
    "        def shop_oder_status(site,po):\n",
    "            table='SHOP_ORDER' \n",
    "            # site=3400\n",
    "            df=mes.mesquery(\"\"\"\n",
    "                        select * from WPPUSER.{0}  \n",
    "\n",
    "                            where ROWNUM <10    \n",
    "                           and site='{1}'\n",
    "                           \n",
    "                            and shop_order = '{2}'\n",
    "                            or shop_order in ({3})\n",
    "                         \"\"\".format(table,site,po,query))\n",
    "            return df\n",
    "        \n",
    "        po_status_df=shop_oder_status(site,po)\n",
    "        \"Check SHOP_ORDER Table {}\".format(len(po_status_df))\n",
    "        if len(po_status_df) >0:\n",
    "            st.table(po_status_df)\n",
    "            qty_build=po_status_df.qty_to_build.iloc[0]\n",
    "            qty_done=po_status_df.qty_done.iloc[0]\n",
    "            qty_released=po_status_df.qty_released.iloc[0]\n",
    "            qty_released\n",
    "\n",
    "            st.sidebar.text(\"qty_released: {}\".format(qty_released))\n",
    "            st.sidebar.text(\"qty_done: {}\".format(qty_done))\n",
    "        else:\n",
    "            \"in info in shop order\"\n",
    "         #---------------------       \n",
    "\n",
    "        st.subheader(\"Step: Check BOM, ROUTING\")\n",
    "        bom_routing_df=mes.mesquery(\"\"\"\n",
    "        select * from WPPUSER.ZME_PN_ROUTING WHERE 1=1 and\n",
    "            site={} and item='{}'\n",
    "        \"\"\".format(site,model)    )\n",
    "        \n",
    "        if len(bom_routing_df)>0:\n",
    "            st.table(bom_routing_df)\n",
    "\n",
    "            st.sidebar.text(\"BOM: {} \".format(bom_routing_df[\"master_bom\"].iloc[0]))\n",
    "            router=bom_routing_df['router'].iloc[0]\n",
    "            st.sidebar.text(\"Routing: {} \".format(bom_routing_df['router'].iloc[0]))\n",
    "\n",
    "            table=\"ROUTER\"\n",
    "            router_df=mes.mesquery(\"\"\"\n",
    "                select * from WPPUSER.{} where site='{}' \n",
    "                and router='{}'\n",
    "                and ROWNUM <= 5\n",
    "                 \"\"\".format(table,site,router))\n",
    "        #     st.table(router_df[:10])\n",
    "        else:\n",
    "            st.sidebar.text(\"NO ROUTING SETUP *\")\n",
    "            \n",
    "            \n",
    "        #-------------------------\n",
    "        st.subheader(\"Step: Check TEST SW MES\")\n",
    "        def model_sw(site,model=''):\n",
    "            table='ZME_TEST_CONFIGURATION' \n",
    "            site=3400\n",
    "            q=(\"\"\"\n",
    "                        select * from WPPUSER.{0}  \n",
    "\n",
    "                            where ROWNUM <10    \n",
    "\n",
    "            and plant ='{1}'\n",
    "            and part_number like '%{2}'\n",
    "                         \"\"\".format(table,site,model))\n",
    "#             df = pd.read_sql(q, engine)\n",
    "            df=mes.mesquery(q)\n",
    "            return df\n",
    "#         model_sw(3400,'GD4130-BK')\n",
    "        sw_df=model_sw(site,model)\n",
    "        if len(sw_df)>0:\n",
    "            sw_df.drop(columns=[\"row_id\"],inplace=True)\n",
    "            st.table(sw_df)\n",
    "        else:\n",
    "            \"No-found-SW\"\n",
    "        st.subheader(\"Step: Check TEST SW ACS for reference\") \n",
    "        def acs_model_sw(model=''):\n",
    "            table='tffc_kicker_table' \n",
    "            site=3400\n",
    "            df=mes.acsquery(\"\"\"\n",
    "                        select * from [ACS EE].dbo.{0}  \n",
    "\n",
    "                            where    1=1\n",
    "\n",
    "             and tffc_kicker_model like '%{1}'\n",
    "                         \"\"\".format(table,model))\n",
    "        #     df = pd.read_sql(q, engine)\n",
    "            return df\n",
    "        sw_df_acs=acs_model_sw(model)\n",
    "#         acs_model_sw(3400,'GD4130-BK')\n",
    "        if len(sw_df_acs)>0:\n",
    "            st.write(sw_df_acs)\n",
    "        else:\n",
    "            st.write(\"no-found-acs-sw\")\n",
    "    \n",
    "        st.sidebar.text(\"---end---\")\n",
    "        st.sidebar.text(\"---follow instruction--->\")\n",
    "\n",
    "    #-----------------------\n",
    "\n",
    "\n",
    "#----------------------------\n",
    "def tracking(sfc, direction=\"down\"):\n",
    "    field_direction=\"sfc_bom_bo\" if direction==\"down\" else \"inventory_bo\"\n",
    "    table='SFC_ASSY' \n",
    "    site=3400\n",
    "    df=mes.mesquery(\"\"\"\n",
    "        select * from WPPUSER.{}  \n",
    "\n",
    "            where ROWNUM <100     \n",
    "             and handle like '{}'\n",
    "             or {} like '%{}'  \n",
    "         \"\"\".format(table,site,field_direction,sfc))\n",
    "\n",
    "    #sfc_bom_bo top_down and sfc_bom_bo like '%G19NAQILN%' \n",
    "    #inventory_bo bot_up\n",
    "    cols=[\"sfc_bom_bo\",\"component_bo\",\"inventory_bo\",\"assembled_date\",\"assembled_by_bo\",\"shop_order_bo\"]\n",
    "    return df[cols]\n",
    "if report_type==\"ASSY tracking up/down\":\n",
    "    #    -----------------------\n",
    "    snlist = st.sidebar.text_area('{0}'.format(\"Nhap serial\"), '')\n",
    "\n",
    "    import pandas as pd\n",
    "\n",
    "    mylist=snlist.split('\\n')\n",
    "    #send list to have list complate\n",
    "    while '' in mylist:\n",
    "        mylist.remove('')\n",
    "    #st.write('My list',mylist)\n",
    "    st.write('qty sns',len(mylist))\n",
    "    \n",
    "    \n",
    "    if st.sidebar.button(\"trackindown\"):\n",
    "\n",
    "        # do main here\n",
    "        dfmain=None\n",
    "        boolfirstdone=False\n",
    "        for item in mylist:\n",
    "            sn=item#row['nam']\n",
    "\n",
    "        #     print(q)\n",
    "            df=tracking(sn,\"down\")\n",
    "\n",
    "            if len(df) >0 and boolfirstdone==False : #loop1\n",
    "        #         print(\"now first row\",df)\n",
    "                boolfirstdone=True\n",
    "        #         print(sn,\"=0\")\n",
    "                dfmain=df\n",
    "        #         print(dfmain)\n",
    "            else:\n",
    "                dfmain=pd.concat([dfmain,df], ignore_index=True)\n",
    "        print(\"done\")\n",
    "        st.table(dfmain)\n",
    "    if (st.sidebar.button(\"trackingup\")):\n",
    "\n",
    "        dfmain=None\n",
    "        boolfirstdone=False\n",
    "        for item in mylist:\n",
    "            sn=item#row['nam']\n",
    "\n",
    "        #     print(q)\n",
    "            df=tracking(sn,\"up\")\n",
    "\n",
    "            if len(df) >0 and boolfirstdone==False : #loop1\n",
    "        #         print(\"now first row\",df)\n",
    "                boolfirstdone=True\n",
    "        #         print(sn,\"=0\")\n",
    "                dfmain=df\n",
    "        #         print(dfmain)\n",
    "            else:\n",
    "                dfmain=pd.concat([dfmain,df], ignore_index=True)\n",
    "        print(\"done\")\n",
    "        st.table(dfmain)\n",
    "\n",
    "\n",
    "        \n",
    "#--------------\n",
    "\n",
    "\n",
    "mylist=mes.getAllMachineList()\n",
    "machine=None\n",
    "# TODO: check serial status\n",
    "try:\n",
    "    machine=st.selectbox(\"chon may tinh\",mylist)\n",
    "except:\n",
    "#     st.selectbox(\"chon may tinh\",mylist)\n",
    "    pass\n",
    "st.write(\"select \",machine)\n",
    "# TODO: Do grant access\n",
    "if st.button(\"grant access\"):\n",
    "    mes.grant_access(machine)\n",
    "#     fr\"done {} machine\".format(len(mylist))\n",
    "    st.write(\"done grant\")\n",
    "# TODO: View db test\n",
    "if st.button(\"view\"):\n",
    "    \n",
    "    df,fn=mes.getHostCommanderlogs(machine,loc=0)\n",
    "    st.table(df.tail(10))\n",
    "# TODO: View HC Log\n",
    "\n",
    "# TODO: logx\n",
    "\n",
    "# TODO: SFC Step status + show current flow"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
